version: '3.8'

services:
  webserver:
      build: ./nginx/
      image: hktari/quotesapp-webserver
      ports:
        - 80:80
        - 443:443
      restart: always
      volumes:
        - ./certbot/www:/var/www/certbot/:ro
        - ./certbot/conf/:/etc/nginx/ssl/:ro
      environment:
        - API_HOST=quotes_api
        - API_PORT=8080
  # certbot:
  #   image: certbot/certbot:latest
  #   volumes:
  #     - ./certbot/www/:/var/www/certbot/:rw
  #     - ./certbot/conf/:/etc/letsencrypt/:rw
  quotes_api:
    container_name: quotes_api
    build:
      context: .
    image: hktari/quotesapp-backend
    ports:
      - '8080:8080'
    environment:
      - PGUSER=hktari
      - PGPASSWORD=123qweAsd.
      - PGDATABASE=quotesapp
      - PGHOST=host.docker.internal
    extra_hosts:
      - host.docker.internal:host-gateway