version: '3.8'

services:
  quotes_api:
    container_name: quotes_api
    image: hktari/quotesapp-backend
    build:
      context: .
    ports:
      - '8080:8080'
    environment:
      - PGUSER=hktari
      - PGPASSWORD=123qweAsd.
      - PGDATABASE=quotesapp
      - PGHOST=host.docker.internal
    extra_hosts:
      - host.docker.internal:host-gateway